services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user1234
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mariadb:
    image: mariadb:11.8
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: collaboard
      MARIADB_USER: user
      MARIADB_PASSWORD: user1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network

  collaboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: collaboard_app
    restart: unless-stopped
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://user:user1234@mongodb:27017/collaboard?authSource=admin
      - DATABASE_URL=mysql://root:root1234@mariadb:3306/collaboard
    depends_on:
      - mongodb
      - mariadb
    networks:
      - app-network

volumes:
  mongo-data:
  mariadb-data:

networks:
  app-network:
    driver: bridge
